---
- name: Blue/Green Deployment Task
  hosts: all
  gather_facts: no

  tasks:
    - name: Login to GitHub Packages
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ gh_user }}"
        password: "{{ gh_pat }}"
        reauthorize: yes

    - name: Pull latest image
      community.docker.docker_image:
        name: "{{ image_to_deploy }}"
        source: pull
        force_source: yes

    - name: Start the Target Container
      community.docker.docker_container:
        name: "web-{{ target_env }}"
        image: "{{ image_to_deploy }}"
        state: started
        recreate: yes
        restart_policy: always
        published_ports:
          - "{{ app_port }}:8000"
        env:
          DB_NAME: "{{ DB_NAME }}"
          DB_USER: "{{ DB_USER }}"
          DB_PASS: "{{ DB_PASS }}"
          DB_HOST: "{{ DB_HOST }}"
        command: >
          sh -c "python3 manage.py migrate --noinput && 
                 python3 manage.py runserver 0.0.0.0:8000"

    - name: Prune old dangling images
      community.docker.docker_prune:
        images: yes
        images_filters:
          dangling: true